version: '3.8'
services:
  appserver:
    image: appserver:pi
    container_name: appserver
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8002:8002
    environment:
      - DEBUG=1
      - NODE_ENV=production
      - TEST=test123
      - DB_HOST=mongo
      - DB_PORT=27017
      - DB_NAME=mbdb
      - JWT_SECRET=1234567890
      - JWT_EXPIRES_IN=3600
      - PORT=8002
      - IS_MONGODB_CLOUD_URL=false
      - MONGODB_CLOUD_URL={PUT_YOUR_MONGO_CLOUD_URL_HERE}
